apiVersion: apps/v1
kind: Deployment
metadata:
  name: skdje
spec:
  replicas: 1
  selector:
    matchLabels:
      app: skdje
  template:
    metadata:
      labels:
        app: skdje
    spec:
      containers:
      - image: okteto.dev/skdje:latest
        name: skdje
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "c9bc8179-b3b7-4e6f-8ad8-8e2a2a0d14d7"
        - name: Vless_Path
          value: "/vl544255"
        - name: Vmess_UUID
          value: "c9bc8179-b3b7-4e6f-8ad8-8e2a2a0d14d7"
        - name: Vmess_Path
          value: "/vm66346"
        - name: Share_Path
          value: "/v2link"
